### User Create
POST http://localhost:3000/api/user
Content-Type: application/json
cors-secret-key: 131312

{
  "email": "in362@naver.com",
  "phoneNumber": "11111",
  "name": "23123",
  "nickName": "jin",
  "password": "123123"
}

### email check
GET http://localhost:3000/api/user/identities?type=email&value=in362@naver.com
Content-Type: application/json


### findEmail
GET http://localhost:3000/api/user/email?name=23123&phoneNumber=11111
Content-Type: application/json


### sendSMS
GET {{baseURL}}/user/sms
